# Generated by Django 4.0.8 on 2025-05-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_priority_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='status',
            field=models.CharField(choices=[('to do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
